spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5437/auth_db
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  access-secret: 'some access secret'
  refresh-secret: 'some refresh secret'
server:
  port: 8082