spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - PrefixPath=/api/v1
            - name: JwtAuthenticationFilter

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - PrefixPath=/api/v1
            - name: JwtAuthenticationFilter

        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - PrefixPath=/api/v1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    instance:
      prefer-ip-address: true

jwt:
  access-secret: 'some access secret'
  refresh-secret: 'some refresh secret'

server:
  port: 8080
