version: '3.9'
services:
  v1_user_db:
    container_name: user-store-db
    image: postgres:15
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_DB=user_store_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
#  v1_keycloak_db:
#    image: postgres:15
#    container_name: keycloak-db
#    ports:
#      - '5436:5432'
#    environment:
#      - POSTGRES_DB=keycloak_db
#      - POSTGRES_USER=keycloak
#      - POSTGRES_PASSWORD=keycloak
#    networks:
#      - keycloak-network
#  keycloak:
#    image: quay.io/keycloak/keycloak:21.0.1
#    ports:
#      - '8180:8080'
#    command: start-dev
#    environment:
#      KC_DB: postgres
#      KC_DB_URL_HOST: v1_keycloak_db
#      KC_DB_URL_DATABASE: keycloak_db
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: keycloak
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    networks:
#      - keycloak-network
#    depends_on:
#    - v1_keycloak_db
#networks:
#  keycloak-network:
#    driver: bridge
