spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5435/user_store_db
    username: user
    password: password
#  security:
#    oauth2:
#      client:
#        registration:
#          userV1-service:
#            provider: keycloak
#            client-id: userV1-service
#            client-secret: Qvck114eOS7PUc5P7QmtkCIYqzPMUQKy
#            scope:
#              - openid
#              - show_users
#              - edit_users
#              - microprofile-jwt
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8180/realms/mcs-realm
#            user-name-attribute: preferred_username
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: user
    password: password
    url: jdbc:postgresql://localhost:5435/user_store_db
    default-schema:
      - user_entity_sc
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8083